name: fantabasket_app_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^5.0.2
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.6.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  pine: ^1.0.3
  pretty_dio_logger: ^1.3.1
  provider: ^6.1.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  google_fonts: ^6.1.0
  page_view_dot_indicator: ^1.1.0
  pair: ^0.1.2
  shared_preferences: ^2.2.2
  faker: ^2.1.0
  skeletonizer: ^1.0.1
  carousel_slider: ^4.2.1
  flutter_typeahead: ^5.0.1
  flutter_localizations:
    sdk: flutter
  pdfx: ^2.6.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  bloc_test: ^9.1.5
  http_mock_adapter: ^0.6.0
  data_fixture_dart: ^2.2.0
  mockito: ^5.4.2
  lottie: ^2.7.0
  auto_route_generator: ^5.0.2
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/regolamento.pdf
    - assets/images/user.png
    - assets/images/basketball.png
    - assets/images/ranking.png
    - assets/images/campo.png
    - assets/images/player.jpeg
    - assets/images/basketbal_big.png
    - assets/images/basketballicon.png
    - assets/images/basketballicon_colored.png
    - assets/images/onlyfanta_logo.svg
    - assets/images/onlyfanta_logo.png
    - assets/lottie/empty.json
    - assets/lottie/trophy.json
  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans_10pt-Regular.ttf
        - asset: assets/fonts/NunitoSans_10pt-Bold.ttf

flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/onlyfanta_logo.png"
  image_path_ios: "assets/images/onlyfanta_logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  #adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  #adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
  #adaptive_icon_monochrome: "assets/images/icon-monochrome-432x432.png" # only available for Android 13 devices and above
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false
